sudo: required
branches:
  only:
  - master
  - docker-rework
services:
- docker
env:
  global:
  - IMAGE_NAME=675906086666.dkr.ecr.us-west-2.amazonaws.com/planet-snowcover:latest
  - DOCKERHUB_IMAGE_NAME="tonycannistra/planet-snowcover:latest"
  - secure: F8tSWqPhaEu8tt8whbLs6mOb0hCQtWsv3yf2q5YQml/grVxqpFCABWJVyKvnvNMsFMPx+1Bz+Lh7MaxmAQCf959xvU4rxYWQf0U9ZXMrPD2DRZFYSws3tmNPovzyqz5si6BCK2UnOsapU6Xu+HGVaRKK5tjbR/eFAUZCzvfjw0RLKh6J5FWmCPEu8GakqGgS141U+s6J62jcFCU37kJ8fVNIp8A4OtKyp2eJJIDrajp+qA3cHIah1IlIX2Pv2EeXLG1tSmeB2wHfgIp638GpfmaMig5ilG6Gsyks18+OLnZR2ZpvDvspzKl+EFihaOXs8KFHoAvShTHDusgwu3JW0rGzL+5XLg6YmUHBN5i7Z8aMDQeQTNaEYZnIjRtO5wIEWDt7RZIERZivMuZABAN5/HnlVRNUef2Cw4FLgE9kdJkwUfyYcwK5QxAEnYZzzKYeNVuTJo+BasSJbISSb35XmVoNLZrTFesoSnP1kuP0X51lX1sswxzhmr6EizR/ABmi+f6DwWzvKLxVOW7Ign94hpMNE6NkFLkuEbqbLImeSxhErQN+XMKIy0kKRnDXNe2IUub7nkGyT0kvrCYJTRpsj26egoOnQ38Dta22ylqS+WzWoIPrFOYMcz7S9xmIUlZ2AzuCTRgYra+QHTzCRwOf2DHp5UVc4Sg+0ar0luovc8o=
  - secure: oBKwv9eaUfxqQyu29dUYBWQFNYUIhoINo2TAEx3rZMIaWRDw7iWrJ9fEpxvbyhdOC6gxSWK6MqPPTh9+hhp9xxcOigxYg7/x2wpGpbjHoRxoz91ggECmBIzYsDFKYw0JdPcyHBW5l4i6ZMcy1AEgxIIoxZ1JAvYd7eWPtqiFCCNINGSJg/dACHcaRs7VuWb3SErvqjzH6h/4iQy7X/8JUfWwXyRtWIRRQEj4a689VZZtN6vpmC8bC9JcAyLljfLan21UOThIsVud/No25zto5TzVGgy5IIKJybV1cxV0qWG7SeFKzoCuRcBV4/dfHkX3pxIOk/hd2rDHIm1q09UmmbJLkr/bW53BoT/K4yUQsTJ5IuZJ37PyQlId8Cspo7gcyithgK6BOmAf8SETJyd8yvBt04w3L11FGDCRs+SNKmSnLX12hOYlz37bDO/Xpbt/dQEe6j7BktuqD6dEo6qXgb78HesHt6fhisOsVNsqIIr0qSAsohlcRJZmvJu+KR4Lwsr6gh6yfJONI1C5gH2CDu5RJuY0M6LpUt5RfIAknD5i/sH84EeZ7hDr4CkvSGPgMrDEb+YTntVF/wXAtAARthX4PZst0ExsNZ1X87QOKIFYfQDbIpIFU9NqRD4/qLZviroCgNgmDyRdIP7GIc4JpoUs76XHPcIGlxWaVedP/Og=
  - secure: iZCoApL4mAGVCfivTjHNp3JAQi3n3V9pWy4VHUPzNZmhXFAMbK2py7e1ZlDtQu6/NRYAjp9zoGgZmFXlQZcNo5nAZszhFM5hiCmhSL/atchSwHTMVnHTp6x8cPLK7uLcftVc8054w8ZaH3X2XaEhdnEw9k/5AM3/w9wM//xMXvbPYm97srx8Ct63sH6pTGiZ24LqFc2TT7oQ2xvGVQPyshm8TFuEmuVxcAMO0aTnK3uZdcMgCnUf/BiObajc9/U5sl+dO1CVUwi0+Zkeg1Xt+lE/2/ra8o75o71aWEja8HPSKc73ZOV857SZqBHTpyCggjMyvKAoXPfiMEVLZlVZeWoqAZOGdDCnZ4COGlLEclIuMlVAJ3qFPaIo5MvxARNnx5iCCrzkXnUZJqyzphK41sRJxZvMrfuk44arH0wEr2Gd3cffIb9Tz71bCW3s8wnOJfjzZi8+bvFeam6MT0Z2EPTw4qfMAwsO3WPorT5JDCCYBS6jzpgupNs7rKZD7t0i+sWXAR7tAL2VdWrwaQWYdUum0NzADXPWv0fqg7UoDqzgkFT/+QJjGHnx7FeDaUlmx5MCmkv6mB+tRraknIwZi235WPA8VmPZTuLU4N5X/xJKXBOSjh769bC0/iRB0UGOz3J4aVOYhF8CksASXciNIWrnssZlPB7tBsqFaxWX7GU=
  - secure: f6GxMEfLR+qjbYKzvZoGnuDzjRF6BNFTIURpX2iqbcryApdVO9VUYZ0RTjtP5E9WZ39zKenoFGd3PVFMH/IgxDOI2cgHu/DFCKZ1f8WGJ2QkXNvVcy6JcC3yqIXgn/VAT/whqPW7AlGU9xxl6fJhNGmgfQHK89SS038jdy8GtlDi7MIM+3yBOn1ck7w/QwjOYbxrZS8vi+GrrtGIy5o65Td/vC9X0KSD6C/24GmVNX5f1qENNYwPmKEwgK2+S/i9jYudyfaAGq0WYDm7OqZWs67Yy/OlUEzW/iZRieKNEy7Ah1wEbUHopzs6fuHfLn3S5O1DeAX8WaK2G7U8DgnENRLMQ0yd4ukBS3szBKoHSfd763HPAH0EOm7wa9djwDFlb86E6kgd3DiuZMauZIahYU+0WyA07LmBtkkf/05JaDoQ3grTtKsqSDHDQsoPBPF8pfrKH68aKlHOAMmbpDjTDOkD4d8fnAsJDLGf1VvwM8QXxkOgpMIOQOyiVfzl0A8Irt7mZ3NGCvRhXHmKvCC1i/iAtDdX7Mn6VtQ9k9Ho3ETMMYOlm0iyb58SNamE6pm/Nbccs8PJzEViDbgDtM9xX1ZVzDGEJE1pQ4VXI9AIYWDMeGaz+GMBt2XkeuJ75gLvM7ScOAecOHVAgERU+rERHI2WWCq1i+/SbVc4q1SktlY=
before_script:
- docker pull "$IMAGE_NAME" || true
script:
- if test -z "$AWS_ACCESS_KEY_ID"; then echo "AWS ACCESS KEY empty"; fi;
- if test -z "$AWS_SECRET_ACCESS_KEY"; then echo "AWS SECRET empty"; fi;
- bash ./environment/create-aws-creds.sh
- stat ./environment/aws_config
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" --file environment/Dockerfile
  .
after_script:
- docker images
after_success:
- docker --version
- pip install --user awscli
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- aws configure set default.region us-west-2
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --no-include-email --region us-west-2)
- docker push "$IMAGE_NAME"
- docker logout
- docker login --username=${DOCKERHUB_USER} --password=${DOCKERHUB_PASS}
- docker tag $IMAGE_NAME $DOCKERHUB_IMAGE_NAME
- docker push "$DOCKERHUB_IMAGE_NAME"
