sudo: required
branches:
  only:
  - master
  - docker-rework
services:
- docker
env:
  global:
  - IMAGE_NAME=675906086666.dkr.ecr.us-west-2.amazonaws.com/planet-snowcover:latest
  - secure: uQL+oqXH2wt7UoKhScbjxJhl06NiPLef1+jJbffTOxgKBTaEI9iWz/NlxkGCUYf7DIgQvd1rQ3/jFDHwtNdyslcxyuDypk9rt8Yl03US9AFgcn53OHDDpaM9bnBvMU/a4bPNoBunY84KWPx+v+YEOcPQaMn6oF/6qf4itvDSRWS76113Dm7p0myxDrfuXDipgOsDecE0mioIjnE1KS+2s8EhoYhfr7M7ibIVx/1XZgx/Woh9v4JkRrjrVEqW6pugTVAoAtYGNt4SPx/iGvzV35s5HJlF5yKZlTbrc09HkcosfwqieHKn+X88VY/dNdkhjPjeSS8iVepsQTNL3JFi16xZq6rwzVpSRxf5iFgfkbFW8xStGmzxyeo0b/ALsq27MKDnGEdKTp4zZOkyCjg5iRBGyorO34K8WYEt+4s+1P2rcZM1RwLE3tgdXE3ttwA7sqJBRciHIXlUwvTTsapiWpYZ94rivqVLeLtsvulBmHNlgxdgVwOkxGGupX0c6RC3slSdtJdGMDua58IKN84bwsT03jyKXhpuw2MjSd5oN/BB/9N39mV3md/qKsMWF2PTeo1RoD7gL7F+ZoCHt2ahEypPYbEWkt3Hb2WH2PlcpdYqI6OkRn8InZLlQ/oVaB3dF1eK8rMSyN4tqUuU7g1JW+9gVE+t8qDg4yf9Clvi/RU=
  - secure: IA+WnzHW6AfEpAx+3fmpW22uV8+Sc6pAFzy/1ALlrjJ/1Tq1wr6OhJbrNwRlPEWsyMw94nTE+K52+Ss9MoKjE1NXnFBCpk+94cP0WhnMxcVoc+MGqH4LHSdjawQRJ4+a22vs+HZNzP/zDKDjbsPWqoEkgODRu1Sf9ImPAPq66eEV+9pBoH81bt+k8deYejz5gkZfzOYqJix1byXNyao/AEGBsY70f9YM3/DsI3lhr417NLZ+TZ83n0Iu7mKnKo+JnQBLX2XkiCzGAhRdi3a+jRiIlrE6cvIPp1L1IH5A2eNFy31Dc5SEnkgATjEYCHQJwA7qU1RMGT/9iTACYP7gDn/QxLs7aytCh9GST6XVGkh5RFuRIkJoP7p764C+yE47vyu9uyskfa7qXXK7H+Sk0NATopoLhUXOJLCff6TdtByILrvRltthP4Te4s45watpPVpGaQ86hDtpWPAUD7CUt9dbxQP7HmoCbfCRp4Xi/CMyy8vad2OGIdDgGPt2qV/JBSGOjRt2oAv150taNpnXyJ7FTU4rpuFSiKRxE6ZJ4NWqEHJQkbAOfGasNnvwlYb1Sz/HUocRkgm3hdOj4tux2sdeUDaRaq8fb2+ilzLq0eguy78uKpP/gHCDVlAzXRol+9dNcWKFeMz/cv3XOfBMEBTkEo1I1H+FPaODxvWqKCs=
before_script:
- docker pull "$IMAGE_NAME" || true
script:
- if test -z "$AWS_ACCESS_KEY_ID"; then echo "AWS ACCESS KEY empty"; fi;
- if test -z "$AWS_SECRET_ACCESS_KEY"; then echo "AWS SECRET empty"; fi;
- bash ./environment/create-aws-creds.sh
- stat ./environment/aws_config
- travis_wait 30 docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" --file environment/Dockerfile .
after_script:
- docker images
after_success:
- docker --version
- pip install --user awscli
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- aws configure set default.region us-west-2
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --no-include-email --region us-west-2)
- docker push "$IMAGE_NAME"
