sudo: required
branches:
  only:
  - master
  - docker-rework
services:
- docker
env:
  global:
  - IMAGE_NAME=675906086666.dkr.ecr.us-west-2.amazonaws.com/planet-snowcover:latest
  - DOCKERHUB_IMAGE_NAME="tonycannistra/planet-snowcover:latest"
  - secure: F8tSWqPhaEu8tt8whbLs6mOb0hCQtWsv3yf2q5YQml/grVxqpFCABWJVyKvnvNMsFMPx+1Bz+Lh7MaxmAQCf959xvU4rxYWQf0U9ZXMrPD2DRZFYSws3tmNPovzyqz5si6BCK2UnOsapU6Xu+HGVaRKK5tjbR/eFAUZCzvfjw0RLKh6J5FWmCPEu8GakqGgS141U+s6J62jcFCU37kJ8fVNIp8A4OtKyp2eJJIDrajp+qA3cHIah1IlIX2Pv2EeXLG1tSmeB2wHfgIp638GpfmaMig5ilG6Gsyks18+OLnZR2ZpvDvspzKl+EFihaOXs8KFHoAvShTHDusgwu3JW0rGzL+5XLg6YmUHBN5i7Z8aMDQeQTNaEYZnIjRtO5wIEWDt7RZIERZivMuZABAN5/HnlVRNUef2Cw4FLgE9kdJkwUfyYcwK5QxAEnYZzzKYeNVuTJo+BasSJbISSb35XmVoNLZrTFesoSnP1kuP0X51lX1sswxzhmr6EizR/ABmi+f6DwWzvKLxVOW7Ign94hpMNE6NkFLkuEbqbLImeSxhErQN+XMKIy0kKRnDXNe2IUub7nkGyT0kvrCYJTRpsj26egoOnQ38Dta22ylqS+WzWoIPrFOYMcz7S9xmIUlZ2AzuCTRgYra+QHTzCRwOf2DHp5UVc4Sg+0ar0luovc8o=
  - secure: oBKwv9eaUfxqQyu29dUYBWQFNYUIhoINo2TAEx3rZMIaWRDw7iWrJ9fEpxvbyhdOC6gxSWK6MqPPTh9+hhp9xxcOigxYg7/x2wpGpbjHoRxoz91ggECmBIzYsDFKYw0JdPcyHBW5l4i6ZMcy1AEgxIIoxZ1JAvYd7eWPtqiFCCNINGSJg/dACHcaRs7VuWb3SErvqjzH6h/4iQy7X/8JUfWwXyRtWIRRQEj4a689VZZtN6vpmC8bC9JcAyLljfLan21UOThIsVud/No25zto5TzVGgy5IIKJybV1cxV0qWG7SeFKzoCuRcBV4/dfHkX3pxIOk/hd2rDHIm1q09UmmbJLkr/bW53BoT/K4yUQsTJ5IuZJ37PyQlId8Cspo7gcyithgK6BOmAf8SETJyd8yvBt04w3L11FGDCRs+SNKmSnLX12hOYlz37bDO/Xpbt/dQEe6j7BktuqD6dEo6qXgb78HesHt6fhisOsVNsqIIr0qSAsohlcRJZmvJu+KR4Lwsr6gh6yfJONI1C5gH2CDu5RJuY0M6LpUt5RfIAknD5i/sH84EeZ7hDr4CkvSGPgMrDEb+YTntVF/wXAtAARthX4PZst0ExsNZ1X87QOKIFYfQDbIpIFU9NqRD4/qLZviroCgNgmDyRdIP7GIc4JpoUs76XHPcIGlxWaVedP/Og=
before_script:
- docker pull "$IMAGE_NAME" || true
script:
- if test -z "$AWS_ACCESS_KEY_ID"; then echo "AWS ACCESS KEY empty"; fi;
- if test -z "$AWS_SECRET_ACCESS_KEY"; then echo "AWS SECRET empty"; fi;
- bash ./environment/create-aws-creds.sh
- stat ./environment/aws_config
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" --file environment/Dockerfile
  .
after_script:
- docker images
after_success:
- docker --version
- pip install --user awscli
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- aws configure set default.region us-west-2
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --no-include-email --region us-west-2)
- docker push "$IMAGE_NAME"
- docker logout
- docker login --username=${DOCKERHUB_USER} --password=${DOCKERHUB_PASS}
- docker tag $IMAGE_NAME $DOCKERHUB_IMAGE_NAME
- docker push "$DOCKERHUB_IMAGE_NAME"
