sudo: required
branches:
  only:
  - master
  - docker-rework
services:
- docker
env:
  global:
  - IMAGE_NAME=675906086666.dkr.ecr.us-west-2.amazonaws.com/planet-snowcover:latest
  - secure: gSWCr9WrHDAX4TumbcErpKLk7CJDeoeRAp6sg6Y+lqm3BwkKyPg1+CXe5Y43tEEkScPMVmPG7wioOlFQ3zLVeVGczPoOKoI4CiGN3OYUhLtiK8dAMUIysSsFwoA06dwS6p3sp7QIjIorrCQ87b6o3iVhD7F/G/fDRvWyLf8vl2KncZWNTTatFyBl+Did6NYvu4MH6bzbj/9sQ+nGa36rbDf7RvsinH66BRVMWVoZz5QX/HysC3X0zcSVTb+B9l+Y0jJWgp5kN6GN8Q+xlM7kQiSmSObNQpKdDxk5g4Pcgp4Sy4IBTSz+ssaiI7WYrskLZn/BXyE4bTaPR7FIwN3yPglvwnYin2GBwlt2rNW0PwGdB2Gi/v2ziUJNtn8gtWaUMi8n1MKjCgaYw/cfL/QX3rlANNHy+c8wdlpeLS0qUly2SwoKBO37Hn5Wm2pYVrkPY38EqZ9a08Ak/zeh5f/mW8cMX2+ROjyaH5o1UQPybyzMBD1XaMmG+aUlHBsMExclvnphGiBVTE65cfplR3LmnO2H11wH3VMD8JinslobaThSOAyAv7mAg+AZAcYxqw2t1mMHblkzB3uQtkiIj6L4KHIve9soeEiAmw39R8nxJgKOoi1O5OBh+UtYJfmEgzjmoGDqehKEbn/UZrkYzUcg3aZg438rMCVYWWdAJaTLxRA=
  - secure: KjJeVL2SjicpgcsB3X407exI3l+dqEWy2tsSdN6f3WyMvYR/auccx3lg+Pgffm//+c7js9O4ZCkVheLc7PjLDTKAkaTm6TOK9VaD6Cnp4IhKbFcabvTEUE+nwmvZX6RXCD/qyMSuppITMtUnSxzeBAJQXdq0OiUjb3WYC5nsgeUE3Hc7FTmP5xlawsFPCOjRZVUDQzQqPHecx0Nv+FzEItAzvIGxbJuRCKcZfAQiLUFs/7Clm5D98HgwBwUwuKlSxtiA/KIWd3tHbqP9nqXkpzi6VKdJgBkND3s0zlFGqG8hSYC44b4mGW9nhqL8jLv2std6IZoRVLjudlmbtZp2ZDkPACqJOC+zNFRboYEI7v8oxV4mPmxtkCIXQy+vmW80LjUaZn2Zaj6MHEHjNEdeavOwNYU5ciVimSMF458BkdDzjvDmSvlpiRH+5FeRMbQIuzs2SXNAMp6x17eGrZ42AxdhLEOy11H7BxxDd61dP8iQ2ib1Wifd+JDgTgBZeZFOEU81mui/ycsZVmusp7GEcN0oy9gCo1tQUr5+ER6VXMebLXqgQMI5p851VfcZQ5J0n4lXuYng1IKpSOFAGCnilpuhss8XjBEP/GQ1YXS0ksBBfbd9ZZJOOzQGq5rE55ltBP1YKk5Ah5orRn2APoGJtyfWHEA8tFXC5inCTEmf1VQ=
before_script:
- docker pull "$IMAGE_NAME" || true
script:
- if test -z "$AWS_ACCESS_KEY_ID"; then echo "AWS ACCESS KEY empty"; fi;
- if test -z "$AWS_SECRET_ACCESS_KEY"; then echo "AWS SECRET empty"; fi;
- bash ./environment/create-aws-creds.sh
- stat ./environment/aws_config
- travis_wait 30 docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" --file environment/Dockerfile .
after_script:
- docker images
after_success:
- docker --version
- pip install --user awscli
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- aws configure set default.region us-west-2
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --no-include-email --region us-west-2)
- docker push "$IMAGE_NAME"
